### ISSUE TITLE
Could not load my own score into online UI or docker image (locally)

### ISSUE THREAD

**Issue by gnai** [upulkkis/orchestration-analyzer#2]
I couldn't load my own music score from my machine into your online UI. Even while running that image locally with the docker container.

**Comment by upulkkis** [comment]
Thank you for trying the app. What type of file your score was? Uncompressed MusicXML should work.

**Comment by gnai** [comment]
It's a musicxml file. the window for uploading from a local machine pops out and you selected and move forward, but nothing loads in. even after I waited, should it be a browser problem maybe ? (I am using Chrome)

**Comment by upulkkis** [comment]
Hmm, I must look into that. My rig is windows pc with chrome and musicxml from finale. The file header must be "data:text", otherwise the program will raise an error. Can you check that the header in your file is of right type?

**Comment by SuperShinyEyes** [comment]
@Gnai If possible, could you share the score you're having a problem with?

**Comment by upulkkis** [comment]
I made changes to the online version which might help you to load your score.

**Comment by gnai** [comment]
Thank you, ill try it out soon. I couldn't share my score before.

**Comment by upulkkis** [comment]
Ok, please notice the new cached version of the program in the new branch. It uses the redis-cache to speed up the calculation. The online version of that is in http://beta.score-tool.com
